#!/usr/bin/env bash

url='http://download.tibia.com/tibia.x64.tar.gz'
zip_file='/tmp/tibia.x64.tar.gz'
home_dir=~/tibia11

wget "${url}" -O "${zip_file}"
mkdir "${home_dir}"
tar xf "${zip_file}" -C "${home_dir}" --strip-components 1
rm "${zip_file}"
